---
title: "Simulation - Covariate Evaluation"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
    toc_collapsed: yes
    theme: lumen
    css: assets/styles.css
---

# Set Up

## Notes

SelectorPlotFunction is wrong The non-identical errors at the end are most likely due to the breaking ties distance metric at the end. It's probably throwing away the remaining data that are less than SelectorN/not making the distance metric working \## Libr.

```{r message=FALSE, warning=FALSE}
library(MASS)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(class)
library(glmnet)
library(nnet)
library(RcppAlgos)  #TVA
library(data.table) #TVA
```

## Load Functions

```{r}
rm(list=ls())
directory = "/Users/simondn/Documents/RashomonActiveLearning/"

if(exists("directory")){
  source(paste0(directory,"Code/functions/Auxiliary/LoadFunctions.R"))
  }else if(!exists("directory")){source("Code/functions/Main/LoadFunctions.R")}

```

# Beta Comparison

```{r}
CoefModelListRandom = numeric(length = length(ModelListRandom) * length(TrueBetas)) %>%
  matrix(nrow = length(ModelListRandom),
         ncol = length(TrueBetas))
CoefModelListBreakingTies = CoefModelListRandom
DifferenceModelListRandom = numeric(length = nrow(CoefModelListRandom))
DifferenceModelListBreakingTies = numeric(length = nrow(CoefModelListRandom))

for(i in 1:length(ModelListRandom)){
  # CoefModelListRandom[i,] = as.numeric(coef(ModelListRandom[[i]])[-1])
  # CoefModelListBreakingTies[i,] = as.numeric(coef(ModelListBreakingTies[[i]])[-1])
  CoefModelListRandom[i,] = as.numeric(coef(ModelListRandom[[i]]))
  CoefModelListBreakingTies[i,] = as.numeric(coef(ModelListBreakingTies[[i]]))
}
```

```{r}
CovariateLook = 2
for(j in 1:length(ModelListRandom)){
  DifferenceModelListRandom[j] = abs(CoefModelListRandom[j,CovariateLook] - TrueBetas[CovariateLook])
  DifferenceModelListBreakingTies[j] = abs(CoefModelListBreakingTies[j,CovariateLook] - TrueBetas[CovariateLook])
}
```

```{r}
CovariateDiffError = data.frame(cbind(DifferenceModelListRandom,DifferenceModelListBreakingTies)) %>%
    mutate(iter = 1:length(DifferenceModelListRandom)) %>%
    pivot_longer(-iter)
colnames(CovariateDiffError) = c("iter", "SelectorType", "error")

  ### Plot ###
CovariateDiffPlot = ggplot() +
    geom_line(data = CovariateDiffError,
              mapping = aes(x = iter, y = error, color = SelectorType)) +
  ylab(paste0("X",CovariateLook, " LASSO Bias")) +
  ylim(0,1)
CovariateDiffPlot
```

```{r}
rbind(TrueBetas,
      CoefModelListRandom[nrow(CoefModelListRandom),],
      CoefModelListBreakingTies[nrow(CoefModelListBreakingTies),]) -> CoefficientResults
rownames(CoefficientResults) = c("True", "Random", "BreakingTies")
colnames(CoefficientResults) = paste0("X", 1:K)
CoefficientResults %>% round(5)
```

# Standard Error of Betas

```{r}
ModelEndBT = ModelListBreakingTies[779][[1]]
```

```{r}
SEList = numeric(4*length(ModelListBreakingTies)) %>%
  matrix(ncol = 4)

for(i in 1:length(ModelListBreakingTies)){
  SEList[i,] = summary(ModelListBreakingTies[[i]])$coefficients[,2]
}
```

```{r}
CovariateSE = SEList %>%
  data.frame %>%
  mutate(iter = SimResultsBreakingTies$InitialTrainingSetN:(nrow(SEList)+SimResultsBreakingTies$InitialTrainingSetN-1)) %>%
    pivot_longer(-iter)
colnames(CovariateSE) = c("iter", "Covariate", "SE")

  ### Plot ###
CovariateDiffPlot = ggplot() +
    geom_line(data = CovariateSE,
              mapping = aes(x = iter, y = SE, color = Covariate)) +
  ylab("Number of annotated observations")
  # xlim(700,800) +
  # ylim(0, 0.2)
CovariateDiffPlot
```
