---
title: "German Credit Example"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
    toc_collapsed: yes
    theme: lumen
    css: assets/styles.css
---

# Set Up

## Notes

## Libr.

```{r message=FALSE, warning=FALSE}
library(MASS) 
library(tidyverse)
library(ggplot2) 
library(dplyr)
library(class)
library(glmnet)
library(nnet)
library(RcppAlgos)   #TVA
library(data.table)  #TVA
library(rashomontva) #TVA
```

## Rm. Var.

```{r}
rm(list=ls())
```

## Functions

```{r}
directory = "/Users/simondn/Documents/RashomonActiveLearning/"

if(exists("directory")){
  source(paste0(directory,"Code/functions/Auxiliary/LoadFunctions.R"))
  }else if(!exists("directory")){source("Code/functions/Main/LoadFunctions.R")}

```

# Generate Data

## Data
```{r}
data("diamonds")
dat = diamonds

dat = dat %>%
  mutate(carat = factor(case_when(carat <= 0.5 ~ 1,
                                     carat > 0.5 & carat <= 1 ~ 2,
                                     carat > 1 & carat <= 2 ~ 3,
                                     carat > 2 ~ 4),
                        ordered = TRUE),
         cut = factor(case_when(cut == "Fair" ~ 1,
                                cut == "Good" ~ 2,
                                cut == "Very Good" ~ 3,
                                cut == "Premium" ~ 4,
                                cut == "Ideal" ~ 5
                                ),
                      ordered = TRUE),
          color = factor(case_when(color == "J" ~ 1,
                                   color == "H" ~ 2,
                                   color == "I" ~ 3,
                                   color == "G" ~ 4,
                                   color == "F" ~ 5,
                                   color == "E" ~ 6,
                                   color == "D" ~ 7),
                         ordered = TRUE),
         clarity = factor(case_when(clarity == "I1" ~   1,
                                    clarity == "SI2" ~  2,
                                    clarity == "SI1" ~  3,
                                    clarity == "VS2" ~  4,
                                    clarity == "VS1" ~  5,
                                    clarity == "VVS2" ~ 6,
                                    clarity == "VVS1" ~ 7,
                                    clarity == "IF" ~   8),
                          ordered = TRUE),
         ID = 1:nrow(dat),
         price = (price-mean(price))/sd(price)
         ) %>%
  dplyr::select(ID, price, carat, cut, color, clarity)
```

```{r}
Model = lm(price ~ carat + cut + color + clarity, data = dat)
PredictedValues = predict(Model)
mean((PredictedValues- dat$price)^2)
```



# Inputs
```{r}
### Input ###
LabelName = "price"
SelectorN = 1
seed = 1
TestProportion = 0.2
SelectorN = 1
InitialN = 10
CovariateList = c("carat",
                  "cut",
                  "color")
RashomonParameters = list(H = Inf,                # Maximum number of pools/splits
                          R = c(5,6,7),         # Bins of each arm (assume 0 exists)
                          reg = 0.1,              # Penalty on the splits
                          theta = 0.1,     # Threshold
                          inactive = 0)
BigDat = dat
dat = dat[sample(1:nrow(dat), 100),]
```




### Rashomon Test
```{r}
### Parameters ###
N = nrow(dat)
M = length(CovariateList)
K = RashomonParameters$K

### Rashomon Profiles ###
NewDat = assign_universal_label(dat, arm_cols = CovariateList)
StartTime = Sys.time()
aggregate_rashomon_profiles(data.frame(NewDat),                 # TrainingSetTrainingData
                            value = LabelName,                  # Response names
                            arm_cols = CovariateList,           # Covariate names
                            M = length(CovariateList),          # Number of covariates
                            H = RashomonParameters$H,           # Maximum number of pools/splits
                            R = RashomonParameters$R,           # Bins of each arm (assume 0 exists)
                            reg = RashomonParameters$reg,       # Penalty on the splits
                            theta = RashomonParameters$theta,   # Threshold
                            inactive = RashomonParameters$inactive
                            ) -> RashomonProfiles  # Losses will always be the last one - (active arms)
RashomonSetTime = Sys.time() - StartTime
RashomonSetNum = length(RashomonProfiles[[1]])
RashomonMakeObjects = make_rashomon_objects(RashomonProfiles)
```



```{r}
SelectorType = "Random"
ModelType = "Factorial"
iter=1
```

```{r}
aggregate_rashomon_profiles(data.frame(dat),                                  # TrainingSetTrainingData
                              value = LabelName,                       # Response names
                              arm_cols = CovariateList,                # Covariate names
                              M = length(CovariateList),               # Number of covariates
                              H = RashomonParameters$H,                # Maximum number of pools/splits
                              R = RashomonParameters$R,                # Bins of each arm (assume 0 exists)
                              reg = RashomonParameters$reg,            # Penalty on the splits
                              theta = RashomonParameters$theta,        # Threshold; determine relative to best model
                              inactive = RashomonParameters$inactive
                              )
```


## Algorithm
```{r}
SimulationFunc(dat = dat,
               LabelName = LabelName,
               CovariateList = CovariateList,
               TestProportion = TestProportion,
               SelectorType = "Random",
               SelectorN = SelectorN,
               ModelType = "Factorial",
               InitialN = InitialN,
               RashomonParameters = RashomonParameters,
               seed = seed) -> SimResultsBreakingTiesRandom
```

```{r}
SimulationFunc(dat = dat,
               LabelName = LabelName,
               CovariateList = CovariateList,
               TestProportion = TestProportion,
               SelectorType = "BreakingTies",
               SelectorN = SelectorN,
               ModelType = "Factorial",
               InitialN = InitialN,
               RashomonParameters = RashomonParameters,
               seed = seed) -> SimResultsBreakingTiesFactorial
```

```{r}
SimulationFunc(dat = dat,
               LabelName = LabelName,
               CovariateList = CovariateList,
               TestProportion = TestProportion,
               SelectorType = "BreakingTies",
               SelectorN = SelectorN,
               ModelType = "RashomonLinear",
               InitialN = InitialN,
               RashomonParameters = RashomonParameters,
               seed = seed) -> SimResultsBreakingTiesRashomon

```

## Visualize



```{r}
# ClassErrorPlotBreakingTies
# ClassErrorPlotRandom
# RandomPlot
# BreakingTiesPlot
SelectorTypeComparisonPlot
```

