---
title: "German Credit Example"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
    toc_collapsed: yes
    theme: lumen
    css: assets/styles.css
---

# Set Up

## Notes

## Libr.

```{r message=FALSE, warning=FALSE}
library(MASS)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(class)
library(glmnet)
library(caret)
library(nnet)
library(RcppAlgos)  #TVA
library(data.table) #TVA
```

## Rm. Var.

```{r}
rm(list=ls())
```

## Functions

```{r}
rm(list=ls())
directory = "/Users/simondn/Documents/RashomonActiveLearning/"

if(exists("directory")){
  source(paste0(directory,"Code/functions/Main/LoadFunctions.R"))
  }else if(!exists("directory")){source("Code/functions/Main/LoadFunctions.R")}
```

# Generate Data

## Data
```{r}
data(GermanCredit)
dat = GermanCredit %>% 
  mutate(ID = 1:nrow(GermanCredit),
         Class = case_when(Class == "Good" ~ 0,
                           Class == "Bad" ~ 1)) %>%
  mutate(Class = as.factor(Class)) %>%
  rename(Y = Class) %>%
  select(ID,
         Y,
         Duration,
         Amount,
         InstallmentRatePercentage,
         ResidenceDuration,
         Age,
         NumberExistingCredits,
         NumberPeopleMaintenance,
         Telephone,
         ForeignWorker) %>%
  mutate(Telephone = Telephone + 1,
         ForeignWorker = ForeignWorker+1)
```


## Discretize
```{r}
NBins = 3
dat = dat %>% mutate(Duration = ntile(Duration, NBins),
                                       Amount = ntile(Amount, NBins),
                                       Age = ntile(Age, NBins))
```

```{r}
### Rashomon Profiles ###
ColArms = c("Duration",
            "Amount", 
            "InstallmentRatePercentage", 
            "ResidenceDuration", 
            "Age", 
            "NumberExistingCredits",
            "NumberPeopleMaintenance", 
            "Telephone",
            "ForeignWorker")
NewDat = assign_universal_label(dat, arm_cols = ColArms)
aggregate_rashomon_profiles(NewDat,                               # Data
                            value = "Y",                       # Response names
                            arm_cols = ColArms,                # Covariate names
                            M = length(ColArms),               # Number of covariates
                            H = Inf,                           # Maximum number of pools/splits
                            R = (1+c(3,3,4,4,3,4,2,2,2)),
                            reg = 1,                           # Penalty on the splits
                            theta = 30,                         # Threshold; determine relative to best model
                            inactive = 0) -> RashomonProfiles  # Losses will always be the last one - (active arms)
```


```{r}
RashomonProfile = RashomonProfileFunc(dat, K, NBins)
RashomonSetNum = RashomonProfile$RashomonSetNum
RashomonLosses = RashomonProfile$RashomonLosses
PredictionObsModel = RashomonProfile$PredictionObsModel
PredictionObsModelRounded = RashomonProfile$PredictionObsModelRounded
RashomonSetTime = RashomonProfile$RashomonSetTime
WholeSetTime = RashomonProfile$WholeSetTime
dat = data.frame(dat)

for(col in 1:ncol(PredictionObsModel)){
   table(PredictionObsModel[,col]) %>% print()
   table(PredictionObsModelRounded[,col]) %>% print()
}
```



# Inputs
```{r}
### Input ###
seed = 1
TestProportion = 0.2
SelectorN = 1
InitialN = 10
ModelType = "Logistic" #Supported Types: Logistic, LASSO, Multinomial, MultinomLASSO, RandomForest
NBins = 3
```

## Algorithm

```{r}
SimulationFunc(dat = dat,
               TestProportion = TestProportion,
               SelectorType = "Random",
               SelectorN = SelectorN,
               ModelType = ModelType,
               InitialN = InitialN,
               seed = seed) -> SimResultsRandom

SimulationFunc(dat = dat,
               TestProportion = TestProportion,
               SelectorType = "BreakingTies",
               SelectorN = SelectorN,
               ModelType = ModelType,
               InitialN = InitialN,
               seed = seed) -> SimResultsBreakingTies

```


## Visualize

```{r}
TestSetPredictionsRandom = SimResultsRandom$TestSetPrediction
TestSetPredictionsBreakingTies = SimResultsBreakingTies$TestSetPrediction

ModelListRandom = SimResultsRandom$ModelList
ModelListBreakingTies = SimResultsBreakingTies$ModelList
```


```{r}
### Stop Iter ###
TailN = 10
VarThreshold = 0.2
ErrorThreshold = 0.3
StopIterRandom = StoppingCriteriaFunc(SimResultsRandom, 
                                      ErrorThreshold = ErrorThreshold,
                                      VarThreshold = VarThreshold, 
                                      TailN = TailN)
StopIterBreakingTies = StoppingCriteriaFunc(SimResultsBreakingTies, 
                                            ErrorThreshold = ErrorThreshold,
                                            VarThreshold = VarThreshold, 
                                            TailN = TailN)

### Plots ###
xupper =NULL
ActiveLearningPlotFunc(Error = SimResultsRandom$Error,
                       StopIter = StopIterRandom,
                       SelectorType = SimResultsRandom$SelectorType,
                       InitialTrainingSetN = SimResultsRandom$InitialTrainingSetN,
                       xupper = xupper) -> RandomPlot

ActiveLearningPlotFunc(Error = SimResultsBreakingTies$Error,
                       StopIter = StopIterBreakingTies,
                       SelectorType = SimResultsBreakingTies$SelectorType,
                       InitialTrainingSetN = SimResultsBreakingTies$InitialTrainingSetN,
                       xupper = xupper) -> BreakingTiesPlot

SelectorTypeComparisonPlotFunc(SimulationType1 = SimResultsRandom,
                               SimulationType2 = SimResultsBreakingTies,
                               StopIter1 = StopIterRandom,
                               StopIter2 = StopIterBreakingTies,
                               xupper = xupper) -> SelectorTypeComparisonPlot

ClassErrorPlotFunc(SimulationResults = SimResultsBreakingTies,
                   xupper = xupper) -> ClassErrorPlotBreakingTies
ClassErrorPlotFunc(SimulationResults = SimResultsRandom,
                   xupper = xupper) -> ClassErrorPlotRandom
```


```{r}
# ClassErrorPlotBreakingTies
# ClassErrorPlotRandom
# RandomPlot
# BreakingTiesPlot
SelectorTypeComparisonPlot
```

