---
title: "Simulation"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
    toc_collapsed: yes
    theme: lumen
    css: assets/styles.css
---

# Set Up

## Notes

SelectorPlotFunction is wrong - The non-identical errors at the end are most likely due to the breaking ties distance metric at the end. It's probably throwing away the remaining data that are less than SelectorN/not making the distance metric working 

## Libr.

```{r message=FALSE, warning=FALSE}
library(MASS)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(class)
library(glmnet)
library(nnet)
library(RcppAlgos)   #TVA
library(data.table)  #TVA
library(rashomontva) #TVA
```


```{r}
# devtools::install_github("Garrett-Allen/rashomon-tva-R")
```
```{r}
# library(rashomontva)
```


## Load Functions

```{r}
rm(list=ls())
directory = "/Users/simondn/Documents/RashomonActiveLearning/"

if(exists("directory")){
  source(paste0(directory,"Code/functions/Auxiliary/LoadFunctions.R"))
  }else if(!exists("directory")){source("Code/functions/Main/LoadFunctions.R")}

```

# Inputs

```{r}
### Input ###
# seed = 1234567890
seed = 10
# N = 375
N = 100
K = 4
NClass = 2
# ClassProportion = c(3/5, 2/5)
ClassProportion = rep(1/NClass, NClass)
CovCorrVal = 0
TestProportion = 0.2
SelectorN = 1
InitialN = 10
NBins = 3
```

```{r}
### Seed ###
set.seed(seed)

### Data ###
DGPResults = GenerateDataFunc(N, K, NClass, ClassProportion, CovCorrVal, NBins = NBins)
dat = DGPResults$dat
TrueBetas = DGPResults$TrueBetas
# dat$Y = as.numeric(dat$Y)
```

```{r}
CovariateList = c("X1", "X2", "X3", "X4")
RashomonParameters = list(K = K, 
                          NBins = NBins,
                          H = Inf,                           # Maximum number of pools/splits
                          R = NBins+1,                       # Bins of each arm (assume 0 exists)
                          reg = 0.1,                         # Penalty on the splits
                          theta = 3,                         # Threshold; determine relative to best model
                          inactive = 0)
```

## Algorithm
```{r}
LabelName = "YStar"
SelectorN = 1
```

```{r}
# ModelType = "Linear"
ModelType = "RashomonLinear"
# ModelType = "Factorial"
SelectorType = "BreakingTies"
iter=1
``` 

```{r}
### Parameters ###
N = nrow(dat)
M = length(CovariateList)
K = RashomonParameters$K
NBins = RashomonParameters$NBins

### Rashomon Profiles ###
NewDat = assign_universal_label(dat, arm_cols = CovariateList)
NewDat$Y = as.numeric(NewDat$Y)
StartTime = Sys.time()
aggregate_rashomon_profiles(data.frame(NewDat),                                  # TrainingSetTrainingData
                            value = LabelName,                       # Response names
                            arm_cols = CovariateList,                # Covariate names
                            M = length(CovariateList),               # Number of covariates
                            H = RashomonParameters$H,                # Maximum number of pools/splits
                            R = RashomonParameters$R,                # Bins of each arm (assume 0 exists)
                            reg = RashomonParameters$reg,            # Penalty on the splits
                            theta = RashomonParameters$theta,        # Threshold; determine relative to best model
                            inactive = RashomonParameters$inactive
                            ) -> RashomonProfiles  # Losses will always be the last one - (active arms)
RashomonSetTime = Sys.time() - StartTime
RashomonSetNum = length(RashomonProfiles[[1]])
RashomonMakeObjects = make_rashomon_objects(RashomonProfiles)

 ### Rashomon Loss ###
RashomonLosses = RashomonProfiles[[2]][[length(RashomonProfiles[[2]])]]$losses

### Rashomon Prediction ###

##
label_data <- prep_data(data.frame(dat), CovariateList, LabelName, RashomonParameters$R, drop_unobserved_combinations = FALSE)
predict(RashomonMakeObjects[[1]], label_data$universal_label)
##

TrainingPredictedLabels = sapply(1:RashomonSetNum,  function(x) predict(RashomonMakeObjects, 
                                                                        NewDat$universal_label, 
                                                                        model_id = x))
TrainingPredictedLabels = round(TrainingPredictedLabels)

# for(i in 1:RashomonSetNum){
#   table(TrainingPredictedLabels[,i]) %>% print()
# }

for(i in 1:RashomonSetNum){
  mean(TrainingPredictedLabels[,i] == NewDat$Y) %>% print
}

```

```{r}
# mean((TrainingPredictedLabels[,1] - dat$YStar)^2) #0.5 something
```


```{r}
SimulationFunc(dat = dat,
               LabelName = LabelName,
               CovariateList = CovariateList,
               TestProportion = TestProportion,
               SelectorType = "BreakingTies",
               SelectorN = SelectorN,
               ModelType = "Factorial",
               InitialN = InitialN,
               RashomonParameters = RashomonParameters,
               seed = seed) -> SimResultsBreakingTiesFactorial
```

```{r}
SimulationFunc(dat = dat,
               LabelName = LabelName,
               CovariateList = CovariateList,
               TestProportion = TestProportion,
               SelectorType = "BreakingTies",
               SelectorN = SelectorN,
               ModelType = "RashomonLinear",
               InitialN = InitialN,
               RashomonParameters = RashomonParameters,
               seed = seed) -> SimResultsBreakingTiesRashomon

```

## Visualize

```{r}
saveRDS(list(SimResultsBreakingTiesFactorial = SimResultsBreakingTiesFactorial,
             SimResultsBreakingTiesRashomon = SimResultsBreakingTiesRashomon,
             Parameters = list(seed = seed,
                               N = N,
                               K = K,
                               NClass = NClass,
                               ClassProportion = ClassProportion,
                               CovCorrVal = CovCorrVal,
                               TestProportion = TestProportion,
                               SelectorN = SelectorN,
                               InitialN = InitialN,
                               NBins = NBins,
                               RashomonParameters = RashomonParameters)),
        file = paste0(directory,"Results/SimulationResults_Seed",seed,".rds"))

# test<- readRDS("/Users/simondn/Documents/RashomonActiveLearning/Results/THISWORKS.rds")
```

```{r}
saveRDS(list(SimResults = SimResultsBreakingTiesFactorial,
             Parameters = list(seed = seed,
                               N = N,
                               K = K,
                               NClass = NClass,
                               ClassProportion = ClassProportion,
                               CovCorrVal = CovCorrVal,
                               TestProportion = TestProportion,
                               SelectorN = SelectorN,
                               InitialN = InitialN,
                               NBins = NBins,
                               RashomonParameters = RashomonParameters)), 
        file = paste0(directory,"Results/NaiveResults_Seed",seed,".RDS"))



saveRDS(list(SimResults = SimResultsBreakingTiesRashomon,
             Parameters = list(seed = seed,
                               N = N,
                               K = K,
                               NClass = NClass,
                               ClassProportion = ClassProportion,
                               CovCorrVal = CovCorrVal,
                               TestProportion = TestProportion,
                               SelectorN = SelectorN,
                               InitialN = InitialN,
                               NBins = NBins,
                               RashomonParameters = RashomonParameters)), 
        file = paste0(directory,"Results/RashomonResults_Seed",seed,".RDS"))
```


```{r}
LoadSimResults1 = readRDS(paste0(directory,"Results/RashomonResults_Seed10.RDS"))
LoadSimResults2 = readRDS(paste0(directory,"Results/NaiveResults_Seed10.RDS"))
SimResults1 = LoadSimResults1$SimResults
SimResults2 = LoadSimResults2$SimResults

```

```{r}
TestSetPredictions1 = SimResults1$TestSetPrediction
TestSetPredictions2 = SimResults2$TestSetPrediction

ModelList1 = SimResults1$ModelList
ModelList2 = SimResults2$ModelList
```

```{r}
### Stop Iter ###
TailN = 10
VarThreshold = 0.2
ErrorThreshold = 0
StopIter1 = StoppingCriteriaFunc(SimResults1,
                                 ErrorThreshold = ErrorThreshold,
                                 VarThreshold = VarThreshold,
                                 TailN = TailN)
StopIter2 = StoppingCriteriaFunc(SimResults2,
                                 ErrorThreshold = ErrorThreshold,
                                 VarThreshold = VarThreshold,
                                 TailN = TailN)

### Plots ###
xupper = NULL

ClassErrorPlotFunc(SimulationResults = SimResults1,
                   xupper = xupper) -> ClassErrorPlot1
ClassErrorPlotFunc(SimulationResults = SimResults2,
                   xupper = xupper) -> ClassErrorPlot2

ActiveLearningPlotFunc(SimResults = SimResults1,
                       StopIter = StopIter1,
                       xupper = xupper) -> ALPlot1

ActiveLearningPlotFunc(SimResults = SimResults2,
                       StopIter = StopIter2,
                       xupper = xupper) -> ALPlot2

SelectorTypeComparisonPlotFunc(SimulationType1 = SimResults1,
                               SimulationType2 = SimResults2,
                               StopIter1 = StopIter1,
                               StopIter2 = StopIter2,
                               xupper = xupper) -> SelectorTypeComparisonPlot
```

```{r}
# ClassErrorPlot2
# ClassErrorPlot1
# ALPlot1
# ALPlot2
SelectorTypeComparisonPlot
```

```{r}
```


```{r}
(cbind(1:length(SimResults1$ErrorVec), abs(SimResults1$ErrorVec - SimResults2$ErrorVec)<1e-3))
```





