---
title: "German Credit Example"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
    toc_collapsed: yes
    theme: lumen
    css: assets/styles.css
---

# Set Up

## Notes

## Libr.

```{r message=FALSE, warning=FALSE}
library(MASS)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(class)
library(glmnet)
library(caret)
```

## Rm. Var.

```{r}
rm(list=ls())
```

## Functions

```{r}
dir = "/Users/simondn/Documents/RashomonActiveLearning/"
source(paste0(dir,"functions/ActiveLearningPlot.R"))
source(paste0(dir,"functions/BreakingTiesSelector.R"))
source(paste0(dir,"functions/ClassErrorPlot.R"))
source(paste0(dir,"functions/GenerateData.R"))
source(paste0(dir,"functions/GenerateData2.R"))
source(paste0(dir,"functions/ModelTypeSwitch.R"))
source(paste0(dir,"functions/RandomSelector.R"))
source(paste0(dir,"functions/RandomStart.R"))
source(paste0(dir,"functions/SelectorSimulationFunc.R"))
source(paste0(dir,"functions/SelectorTypeSwitch.R"))
source(paste0(dir,"functions/SelectorTypeComparisonPlotFunc.R"))
source(paste0(dir,"functions/StoppingCriteria.R"))
source(paste0(dir,"functions/TestError.R"))
source(paste0(dir,"functions/Validation.R"))
```

# Generate Data

## Data
```{r}
# set.seed(1)
data(GermanCredit)
GermanCredit = GermanCredit %>% 
  mutate(ID = 1:nrow(GermanCredit),
         Class = case_when(Class == "Good" ~ 1,
                           Class == "Bad" ~ 2)) %>%
  mutate(Class = as.factor(Class)) %>%
  rename(Y = Class) %>%
  select(ID,
         Y,
         Duration,
         Amount,
         InstallmentRatePercentage,
         ResidenceDuration,
         Age,
         NumberExistingCredits,
         NumberPeopleMaintenance,
         Telephone,
         ForeignWorker)
```

# One Iteration

```{r}
seed = 1
dat = GermanCredit
TailN = 30
TestProportion = 0.2
ErrorThreshold = 0.25
VarThreshold = .1
SelectorN = 1
InitialN = 10
ModelType = "Logistic"
```

```{r warning=FALSE}
SelectorSimulationFunc(dat = dat,
                       TestProportion = TestProportion,
                       TailN = TailN,
                       ErrorThreshold = ErrorThreshold,
                       VarThreshold = VarThreshold,
                       SelectorType = "Random",
                       SelectorN = SelectorN,
                       ModelType = ModelType,
                       InitialN = InitialN,
                       seed = seed) -> SimResultsRandom

SelectorSimulationFunc(dat = dat,
                       TestProportion = TestProportion,
                       TailN = TailN,
                       ErrorThreshold = ErrorThreshold,
                       VarThreshold = VarThreshold,
                       SelectorType = "BreakingTies",
                       SelectorN = SelectorN,
                       ModelType = ModelType,
                       InitialN = InitialN,
                       seed = seed) -> SimResultsBreakingTies
```

```{r}
TestSetPredictionsRandom = SimResultsRandom$TestSetPrediction
TestSetPredictionsBreakingTies = SimResultsBreakingTies$TestSetPrediction
```


```{r}
ActiveLearningPlotFunc(Error = SimResultsRandom$Error,
                       StopIter = SimResultsRandom$StopIter,
                       SelectorType = SimResultsRandom$SelectorType) -> RandomPlot

ActiveLearningPlotFunc(Error = SimResultsBreakingTies$Error,
                       StopIter = SimResultsBreakingTies$StopIter,
                       SelectorType = SimResultsBreakingTies$SelectorType) -> BreakingTiesPlot

SelectorTypeComparisonPlotFunc(SimResultsRandom,SimResultsBreakingTies) -> SelectorTypeComparisonPlot

ClassErrorPlotFunc(SimResultsBreakingTies) -> ClassErrorPlotBreakingTies
ClassErrorPlotFunc(SimResultsRandom) -> ClassErrorPlotRandom
```

```{r}
# RandomPlot
# BreakingTiesPlot
SelectorTypeComparisonPlot
ClassErrorPlotBreakingTies
ClassErrorPlotRandom
```




# Simulation
```{r}
# ### Set Up ###
# dat = GermanCredit
# TailN = 30
# TestProportion = 0.2
# ErrorThreshold = 0.25
# VarThreshold = .1
# SelectorN = 1
# InitialN = 10
# ModelType = "LASSO"
# 
# NSeed = 50
# SimulationRandomModels = vector('list', NSeed)
# SimulationBreakingTiesModels = vector('list', NSeed)
# MyPlots = vector('list', NSeed)
# 
# ### Iteration ###
# for(SeedIter in 1:NSeed){
#   
#   print(SeedIter)
#   
#   ### Random Simulation ###
#   SelectorSimulationFunc(dat = dat,
#                        TestProportion = TestProportion,
#                        TailN = TailN,
#                        ErrorThreshold = ErrorThreshold,
#                        VarThreshold = VarThreshold,
#                        SelectorType = "Random",
#                        SelectorN = SelectorN,
#                        ModelType = ModelType,
#                        InitialN = InitialN,
#                        seed = SeedIter) -> SimulationRandomModels[[SeedIter]]
#   
#   ### Breaking Ties Simulation ###
#   SelectorSimulationFunc(dat = dat,
#                        TestProportion = TestProportion,
#                        TailN = TailN,
#                        ErrorThreshold = ErrorThreshold,
#                        VarThreshold = VarThreshold,
#                        SelectorType = "BreakingTies",
#                        SelectorN = SelectorN,
#                        ModelType = ModelType,
#                        InitialN = InitialN,
#                        seed = SeedIter) -> SimulationBreakingTiesModels[[SeedIter]]
#   
#   ### Plot ###
#   MyPlots[[SeedIter]] = SelectorTypeComparisonPlotFunc(SimulationRandomModels[[SeedIter]],
#                                                        SimulationBreakingTiesModels[[SeedIter]])
# }
#
# for(i in 1:NSeed){
#   print(MyPlots[[i]])
# }
```







