---
title: "Scratch Work"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
    toc_collapsed: yes
    theme: lumen
    css: assets/styles.css
---

# Set Up

## Notes

## Libr.

```{r message=FALSE, warning=FALSE}
library(MASS)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(class)
library(glmnet)
library(caret)
```

## Rm. Var.

```{r}
rm(list=ls())
```

## Functions

```{r}
dir = "/Users/simondn/Documents/RashomonActiveLearning/"
source(paste0(dir,"functions/BreakingTiesSelector.R"))
source(paste0(dir,"functions/GenerateData.R"))
source(paste0(dir,"functions/GenerateData2.R"))
source(paste0(dir,"functions/RandomStart.R"))
source(paste0(dir,"functions/RandomSelector.R"))
source(paste0(dir,"functions/SelectorSimulationFunc.R"))
source(paste0(dir,"functions/StoppingCriteria.R"))
```

# Generate Data

## Data
```{r}
set.seed(2)
data(GermanCredit)
GermanCredit = GermanCredit %>% 
  mutate(ID = 1:nrow(GermanCredit),
         Class = case_when(Class == "Good" ~ 1,
                           Class == "Bad" ~ 2)) %>%
  mutate(Class = as.factor(Class)) %>%
  rename(Y = Class) %>%
  select(ID,
         Y,
         Duration,
         Amount,
         InstallmentRatePercentage,
         ResidenceDuration,
         Age,
         NumberExistingCredits,
         NumberPeopleMaintenance,
         Telephone,
         ForeignWorker)
```

# Model

## Logistic
```{r}
LogModel = glm(Y ~ ., 
               data = GermanCredit,
               family = "binomial")
LogPredicted = 1*(predict(LogModel, newdata = GermanCredit, type = "response")>0.5)
LogPredictedProbabilities = predict(LogModel,
                                    newdata = GermanCredit,
                                    type = "response")
mean(LogPredicted == GermanCredit$Y)
```


## LASSO

```{r}
# Model #
LASSO_Regression = glmnet(x = as.matrix(GermanCredit[, setdiff(names(GermanCredit), c("Y"))]),
                          y = as.matrix(GermanCredit$Y),
                          alpha = 1,
                          family = "binomial")
LASSO_Lambda = min(LASSO_Regression$lambda)

# Training Prediction #
LASSOTrainingPrediction = predict(LASSO_Regression,
                                    newx = as.matrix(GermanCredit[, setdiff(names(GermanCredit), c("Y"))]),
                                    s = LASSO_Lambda,
                                    type = "response")
LASSOTrainingPrediction = ifelse(LASSOTrainingPrediction > 0.5,1,0)+1

mean(LASSOTrainingPrediction != GermanCredit$Y)

```


## Random Selection

```{r}
RandomStart = RandomStartFunc(InitialN=10, dat=GermanCredit)
TrainingSet = RandomStart$TrainingSet
CandidateSet = RandomStart$CandidateSet
```

## Simulation

```{r}
dat = GermanCredit
TailN = 20
ErrorThreshold = 0.2
VarThreshold = .1
TrainingSet = TrainingSet
CandidateSet = CandidateSet
SelectorN = 1

# dat = dat
# TailN = TailN
# ErrorThreshold = ErrorThreshold
# VarThreshold = VarThreshold
# TrainingSet = TrainingSet
# CandidateSet = CandidateSet
# SelectorType = "Random"
# SelectorN = 1
# ModelType = "LASSO"
```



  
```{r warning=FALSE}
SelectorSimulationFunc(dat = dat,
                       TailN = TailN,
                       ErrorThreshold = ErrorThreshold,
                       VarThreshold = VarThreshold,
                       TrainingSet = TrainingSet,
                       CandidateSet = CandidateSet,
                       SelectorType = "Random",
                       SelectorN = 1,
                       ModelType = "Logistic") -> SimResultsRandom

SelectorSimulationFunc(dat = dat,
                       TailN = TailN,
                       ErrorThreshold = ErrorThreshold,
                       VarThreshold = VarThreshold,
                       TrainingSet = TrainingSet,
                       CandidateSet = CandidateSet,
                       SelectorType = "BreakingTies",
                       SelectorN = 1,
                       ModelType = "Logistic") -> SimResultsBreakingTies
```

```{r}
SimResultsRandom$ErrorScatterPlot
SimResultsBreakingTies$ErrorScatterPlot
```
```{r}
LineTypes = c("Random" = "dashed",
              "BreakingTies" = "solid")

ErrorScatterPlot = ggplot() +
    geom_line(mapping = aes(x = 1:length(SimResultsRandom$Error), 
                            y = SimResultsRandom$Error,
                            linetype = "Random")) + 
    geom_line(mapping = aes(x = 1:length(SimResultsBreakingTies$Error), 
                            y = SimResultsBreakingTies$Error,
                            linetype = "BreakingTies")) + 
    geom_vline(xintercept = SimResultsRandom$StopIter, 
               color = "red",
               linetype = "dashed") + 
    geom_vline(xintercept = SimResultsBreakingTies$StopIter, 
               color = "red",
               linetype = "solid") +
# Aesthetics
    xlab("Iterations") +
    ylab("Error") +
    ggtitle("Simulation by Error") +
    theme(plot.title = element_text(size = 15, hjust = 0.5)) +
  xlim(0,200)

ErrorScatterPlot

```