---
title: "Scratch Work"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
    toc_collapsed: yes
    theme: lumen
    css: assets/styles.css
---

# Set Up

## Notes

## Libr.

```{r message=FALSE, warning=FALSE}
library(MASS)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(class)
library(glmnet)
library(nnet)
library(RcppAlgos)
```

## Rm. Var.

```{r}
rm(list=ls())
```

## Functions


```{r}
dir = "/Users/simondn/Documents/RashomonActiveLearning/"

source(paste0(dir,"Code/functions/Selector/BreakingTiesSelector.R"))
source(paste0(dir,"Code/functions/Selector/ModelTypeSwitch.R"))
source(paste0(dir,"Code/functions/Selector/MostUncertainObservation.R"))
source(paste0(dir,"Code/functions/Selector/RandomSelector.R"))
source(paste0(dir,"Code/functions/Selector/RandomStart.R"))
source(paste0(dir,"Code/functions/Selector/SelectorTypeSwitch.R"))
source(paste0(dir,"Code/functions/Selector/StoppingCriteria.R"))
source(paste0(dir,"Code/functions/Selector/TestError.R"))
source(paste0(dir,"Code/functions/Selector/Validation.R"))

source(paste0(dir,"Code/functions/Plots/ActiveLearningPlot.R"))
source(paste0(dir,"Code/functions/Plots/ClassErrorPlot.R"))
source(paste0(dir,"Code/functions/Plots/SelectorTypeComparisonPlotFunc.R"))

source(paste0(dir,"Code/functions/Main/GenerateData.R"))
source(paste0(dir,"Code/functions/Main/GenerateData2.R"))
source(paste0(dir,"Code/functions/Main/GenerateData3.R"))
source(paste0(dir,"Code/functions/Main/RashomonFunc.R"))
source(paste0(dir,"Code/functions/Main/SimulationFunc.R"))
```

## Rashomon Functions
```{r}
source("/Users/simondn/Documents/RashomonActiveLearning/rashomon-tva-R-main/R/aggregate.R")
source("/Users/simondn/Documents/RashomonActiveLearning/rashomon-tva-R-main/R/count.R")
source("/Users/simondn/Documents/RashomonActiveLearning/rashomon-tva-R-main/R/find_rashomon_set.R")
source("/Users/simondn/Documents/RashomonActiveLearning/rashomon-tva-R-main/R/globals.R")
source("/Users/simondn/Documents/RashomonActiveLearning/rashomon-tva-R-main/R/loss.R")
source("/Users/simondn/Documents/RashomonActiveLearning/rashomon-tva-R-main/R/predictions.R")
source("/Users/simondn/Documents/RashomonActiveLearning/rashomon-tva-R-main/R/RashomonSet.R")
source("/Users/simondn/Documents/RashomonActiveLearning/rashomon-tva-R-main/R/rashomontva-package.R")
source("/Users/simondn/Documents/RashomonActiveLearning/rashomon-tva-R-main/R/utils.R")
```

# Generate Data

## Data

```{r}
### Input ###
seed = 123
set.seed(seed)
N = 1000
K = 4
NClass = 2
# ClassProportion = c(3/5, 2/5)
ClassProportion = rep(1/NClass, NClass)
MeanMatrix = rep(0,K)
CovCorrVal = -0.9
```

    
```{r}
### Data ###
DGPResults = GenerateDataFunc3(N, K, NClass, ClassProportion, MeanMatrix, CovCorrVal)
dat = DGPResults$dat
TrueBetas = DGPResults$TrueBetas
```

## Discretize Covariates
```{r}
# NBins = 3
# dat = dat %>% mutate(across(starts_with("X"), ~ ntile(., NBins)))
# dat$Y = as.numeric(dat$Y)
```

### Rashomon Example 

```{r}
# RashomonProfile = RashomonProfileFunc(dat, K, NBins)
# RashomonSetNum = RashomonProfile$RashomonSetNum
# RashomonLosses = RashomonProfile$RashomonLosses
# PredictionObsModel = RashomonProfile$PredictionObsModel
# RashomonSetTime = RashomonProfile$RashomonSetTime
# WholeSetTime = RashomonProfile$WholeSetTime
# dat = data.frame(dat)
```


```{r}
### Visualize ###
# ScatterPlotX1X2 = ggplot(data = dat) +
  # geom_point(mapping = aes(x = X2, y = X4, color = as.factor(Y)))
# ScatterPlotX1X2
```

# Simulation

## Parameters

```{r}
TestProportion = 0.2
SelectorN = 1
InitialN = 10
ModelType = "LASSO" #Supported Types: Logistic, LASSO, Multinomial, MultinomLASSO, RandomForest
```

## Algorithm
```{r}
SimulationFunc(dat = dat,
               TestProportion = TestProportion,
               SelectorType = "Random",
               SelectorN = SelectorN,
               ModelType = ModelType,
               InitialN = InitialN,
               seed = seed) -> SimResultsRandom

SimulationFunc(dat = dat,
               TestProportion = TestProportion,
               SelectorType = "BreakingTies",
               SelectorN = SelectorN,
               ModelType = ModelType,
               InitialN = InitialN,
               seed = seed) -> SimResultsBreakingTies
```

## Visualize
```{r}
TestSetPredictionsRandom = SimResultsRandom$TestSetPrediction
TestSetPredictionsBreakingTies = SimResultsBreakingTies$TestSetPrediction

ModelListRandom = SimResultsRandom$ModelList
ModelListBreakingTies = SimResultsBreakingTies$ModelList
```


```{r}
### Stop Iter ###
TailN = 10
VarThreshold = 0.2
ErrorThreshold = 0.25
StopIterRandom = StoppingCriteriaFunc(SimResultsRandom, 
                                      ErrorThreshold = ErrorThreshold,
                                      VarThreshold = VarThreshold, 
                                      TailN = TailN)
StopIterBreakingTies = StoppingCriteriaFunc(SimResultsBreakingTies, 
                                            ErrorThreshold = ErrorThreshold,
                                            VarThreshold = VarThreshold, 
                                            TailN = TailN)

### Plots ###
xupper =NULL
ActiveLearningPlotFunc(Error = SimResultsRandom$Error,
                       StopIter = StopIterRandom,
                       SelectorType = SimResultsRandom$SelectorType,
                       InitialTrainingSetN = SimResultsRandom$InitialTrainingSetN,
                       xupper = xupper) -> RandomPlot

ActiveLearningPlotFunc(Error = SimResultsBreakingTies$Error,
                       StopIter = StopIterBreakingTies,
                       SelectorType = SimResultsBreakingTies$SelectorType,
                       InitialTrainingSetN = SimResultsBreakingTies$InitialTrainingSetN,
                       xupper = xupper) -> BreakingTiesPlot

SelectorTypeComparisonPlotFunc(SimulationType1 = SimResultsRandom,
                               SimulationType2 = SimResultsBreakingTies,
                               StopIter1 = StopIterRandom,
                               StopIter2 = StopIterBreakingTies,
                               xupper = xupper) -> SelectorTypeComparisonPlot

ClassErrorPlotFunc(SimulationResults = SimResultsBreakingTies,
                   xupper = xupper) -> ClassErrorPlotBreakingTies
ClassErrorPlotFunc(SimulationResults = SimResultsRandom,
                   xupper = xupper) -> ClassErrorPlotRandom
```


```{r}
ClassErrorPlotBreakingTies
ClassErrorPlotRandom
RandomPlot
BreakingTiesPlot
SelectorTypeComparisonPlot
```


# Beta Comparison
```{r}
CoefModelListRandom = numeric(length = length(ModelListRandom) * length(TrueBetas)) %>%
  matrix(nrow = length(ModelListRandom),
         ncol = length(TrueBetas))
CoefModelListBreakingTies = CoefModelListRandom
DifferenceModelListRandom = numeric(length = nrow(CoefModelListRandom))
DifferenceModelListBreakingTies = numeric(length = nrow(CoefModelListRandom))

for(i in 1:length(ModelListRandom)){
  CoefModelListRandom[i,] = as.numeric(coef(ModelListRandom[[i]])[-1])
  CoefModelListBreakingTies[i,] = as.numeric(coef(ModelListBreakingTies[[i]])[-1])
  # CoefModelListRandom[i,] = as.numeric(coef(ModelListRandom[[i]]))
  # CoefModelListBreakingTies[i,] = as.numeric(coef(ModelListBreakingTies[[i]]))
}
```

```{r}
CovariateLook = 2
for(j in 1:length(ModelListRandom)){
  DifferenceModelListRandom[j] = abs(CoefModelListRandom[j,CovariateLook] - TrueBetas[CovariateLook])
  DifferenceModelListBreakingTies[j] = abs(CoefModelListBreakingTies[j,CovariateLook] - TrueBetas[CovariateLook])
}
```


```{r}
CovariateDiffError = data.frame(cbind(DifferenceModelListRandom,DifferenceModelListBreakingTies)) %>%
    mutate(iter = 1:length(DifferenceModelListRandom)) %>%
    pivot_longer(-iter)
colnames(CovariateDiffError) = c("iter", "SelectorType", "error")

  ### Plot ###
CovariateDiffPlot = ggplot() +
    geom_line(data = CovariateDiffError,
              mapping = aes(x = iter, y = error, color = SelectorType)) +
  ylab(paste0("X",CovariateLook, " LASSO Bias")) +
  ylim(0,1)
CovariateDiffPlot
```
```{r}
rbind(TrueBetas,
      CoefModelListRandom[nrow(CoefModelListRandom),],
      CoefModelListBreakingTies[nrow(CoefModelListBreakingTies),]) -> CoefficientResults
rownames(CoefficientResults) = c("True", "Random", "BreakingTies")
colnames(CoefficientResults) = paste0("X", 1:K)
CoefficientResults %>% round(5)
```

# Standard Error of Betas
```{r}
# ModelEndBT = ModelListBreakingTies[771][[1]]
```

```{r}
# SEList = numeric(4*length(ModelListBreakingTies)) %>% 
#   matrix(ncol = 4)
# 
# for(i in 1:length(ModelListBreakingTies)){
#   SEList[i,] = summary(ModelListBreakingTies[[i]])$coefficients[,2]
# }
```

```{r}
# CovariateSE = SEList %>% 
#   data.frame %>%
#   mutate(iter = SimResultsBreakingTies$InitialTrainingSetN:(nrow(SEList)+SimResultsBreakingTies$InitialTrainingSetN-1)) %>%
#     pivot_longer(-iter)
# colnames(CovariateSE) = c("iter", "Covariate", "SE")
# 
#   ### Plot ###
# CovariateDiffPlot = ggplot() + 
#     geom_line(data = CovariateSE,
#               mapping = aes(x = iter, y = SE, color = Covariate)) + 
#   ylab("Number of annotated observations")
#   # xlim(700,800) +
#   # ylim(0, 0.2)
# CovariateDiffPlot
```




