---
title: "SimulationResults Analysis"
author: "Simon Dovan Nguyen"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
    toc_collapsed: yes
    theme: lumen
    css: assets/styles.css
---

# Set Up

## Notes

## Libr.

```{r message=FALSE, warning=FALSE}
library(MASS) 
library(tidyverse)
library(ggplot2) 
library(dplyr)
library(class)
library(glmnet)
library(nnet)
library(RcppAlgos)   #TVA
library(data.table)  #TVA
library(rashomontva) #TVA
```

## Load Functions

```{r}
### Set Up ###
rm(list=ls())
directory = "/Users/simondn/Documents/RashomonActiveLearning/"

### Load Functions ###
if(exists("directory")){
  source(paste0(directory,"Code/functions/Auxiliary/LoadFunctions.R"))
  }else if(!exists("directory")){source("Code/functions/Main/LoadFunctions.R")}
```

## Load Data
```{r}
### Load Data ###
load(paste0(directory, "Results/Extracted/Simulations/VanillaActive3.RData"))
Results_Active3 = OutputVector
rm(OutputVector)
load(paste0(directory, "Results/Extracted/Simulations/VanillaActive4.RData"))
Results_Active4 = OutputVector
rm(OutputVector)
load(paste0(directory, "Results/Extracted/Simulations/VanillaActive5.RData"))
Results_Active5 = OutputVector
rm(OutputVector)
load(paste0(directory, "Results/Extracted/Simulations/VanillaActive6.RData"))
Results_Active6 = OutputVector
rm(OutputVector)
load(paste0(directory, "Results/Extracted/Simulations/VanillaRandom3.RData"))
Results_Random3 = OutputVector
rm(OutputVector)
load(paste0(directory, "Results/Extracted/Simulations/VanillaRandom4.RData"))
Results_Random4 = OutputVector
rm(OutputVector)
load(paste0(directory, "Results/Extracted/Simulations/VanillaRandom5.RData"))
Results_Random5 = OutputVector
rm(OutputVector)
load(paste0(directory, "Results/Extracted/Simulations/VanillaRandom6.RData"))
Results_Random6 = OutputVector

rm(OutputVector)
```

# Plot
## Set Up
```{r}
SelectorTypeComparisonPlotFuncConfidenceBands(Random = Results_Random3$ErrorVec,
                                              Active = Results_Active3$ErrorVec) -> Plot3

SelectorTypeComparisonPlotFuncConfidenceBands(Random = Results_Random4$ErrorVec,
                                              Active = Results_Active4$ErrorVec) -> Plot4

SelectorTypeComparisonPlotFuncConfidenceBands(Random = Results_Random5$ErrorVec,
                                              Active = Results_Active5$ErrorVec) -> Plot5

SelectorTypeComparisonPlotFuncConfidenceBands(Random = Results_Random6$ErrorVec,
                                              Active = Results_Active6$ErrorVec) -> Plot6
```

```{r}
Plot3 = Plot3 + labs(title = "3 useful covariates & 1 useless covariate")
Plot4 = Plot4 + labs(title = "4 useful covariates & 1 useless covariate")
Plot5 = Plot5 + labs(title = "5 useful covariates & 1 useless covariate")
Plot6 = Plot6 + labs(title = "6 useful covariates & 1 useless covariate")
```

## Plot Results
```{r}
Plot3 + ylim(0.9,1.10)
Plot4 + ylim(0.9,1.10)
Plot5 + ylim(0.9,1.10)
Plot6 + ylim(0.9,1.10)
```

# Statistical Testing
```{r}
### Average RMSE at each point ###
MeanRMSE_Random3 = colMeans(Results_Random3$ErrorVec)
MeanRMSE_Active3 = colMeans(Results_Active3$ErrorVec)

MeanRMSE_Random4 = colMeans(Results_Random4$ErrorVec)
MeanRMSE_Active4 = colMeans(Results_Active4$ErrorVec)

MeanRMSE_Random5 = colMeans(Results_Random5$ErrorVec)
MeanRMSE_Active5 = colMeans(Results_Active5$ErrorVec)

MeanRMSE_Random6 = colMeans(Results_Random6$ErrorVec)
MeanRMSE_Active6 = colMeans(Results_Active6$ErrorVec)

### Wilcoxon signed-rank test ###
WSRT3 = wilcox.test(MeanRMSE_Random3, MeanRMSE_Active3, paired = TRUE)
WSRT4 = wilcox.test(MeanRMSE_Random4, MeanRMSE_Active4, paired = TRUE)
WSRT5 = wilcox.test(MeanRMSE_Random5, MeanRMSE_Active5, paired = TRUE)
WSRT6 = wilcox.test(MeanRMSE_Random6, MeanRMSE_Active6, paired = TRUE)

# Print the test result
c(WSRT3$p.value, WSRT4$p.value, WSRT4$p.value, WSRT6$p.value)
```



